include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 안전성
    avoid_print: true
    avoid_dynamic_calls: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true

    # 코드 품질
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    unnecessary_this: true
    unnecessary_late: true

    # 스타일
    always_declare_return_types: true
    annotate_overrides: true
    prefer_single_quotes: true
    sort_constructors_first: true
    use_super_parameters: true

    # 문서화
    public_member_api_docs: false # 초기에는 비활성화

analyzer:
  errors:
    avoid_print: warning
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**
